### ISSUE TITLE
Usage of Django settings variable

### ISSUE THREAD

**Issue by jerinpetergeorge** [IAEA-NDS/cdb#27]
We have been using the settings variables as [**`from cdb.settings import SITE_ROOT_URL, POTENTIAL_URL, POTENTIAL_URI_STEM`**](https://github.com/IAEA-NDS/cdb/blob/d0f5a938e60885348ab19c26dda46b6cec8ca417/cdbmeta/models.py#L10)

This is not the Django way to use the settings. We must import the settings instance as
```python
from django.conf import settings

settings.SITE_ROOT_URL
```

**Comment by xnx** [comment]
Fixed by 1f9b60e7b9
